export const TECH_COLORS: Record<string, string> = {
  react: "bg-cyan-500/90 text-white",
  vue: "bg-emerald-500/90 text-white",
  astro: "bg-orange-500/90 text-white",
  next: "bg-zinc-800 text-zinc-100",
  typeScript: "bg-blue-600/90 text-white",
  javaScript: "bg-amber-400/90 text-zinc-900",
  PHP: "bg-indigo-700/90 text-white",
  laravel: "bg-red-600/90 text-white",
  symfony: "bg-black text-white",
  magento: "bg-orange-600/90 text-white",
  prestashop: "bg-rose-600/90 text-white",
  tailwindcss: "bg-sky-500/90 text-white",
  nodejs: "bg-green-600/90 text-white",
  mysql: "bg-blue-700/90 text-white",
  docker: "bg-blue-500/90 text-white",
  supabase: "bg-emerald-600/90 text-white",
  wordpress: "bg-blue-800/90 text-white",
  vercel: "bg-zinc-900 text-zinc-100",
  git: "bg-orange-600/90 text-white",
  githubActions: "bg-zinc-700 text-zinc-100",
  twig: "bg-emerald-700/90 text-white",
  stimulus: "bg-purple-500/90 text-white",
  redis: "bg-red-600/90 text-white",
  webpack: "bg-sky-600/90 text-white",
  vite: "bg-violet-500/90 text-white",
  framerMotion: "bg-pink-500/90 text-white",
  django: "bg-green-800/90 text-white",
  postgresql: "bg-blue-800/90 text-white",
  ml: "bg-amber-600/90 text-zinc-900",
  resend: "bg-rose-500/90 text-white",
  payload: "bg-indigo-600/90 text-white",
  fastapi: "bg-teal-600/90 text-white",
  sqlite: "bg-sky-700/90 text-white",
};

const TECH_LABELS: Record<string, string> = {
  typeScript: "TypeScript",
  javaScript: "JavaScript",
  tailwindcss: "Tailwind",
  nodejs: "Node.js",
  githubActions: "GitHub Actions",
  twig: "Twig",
  stimulus: "Stimulus",
  webpack: "Webpack",
  vite: "Vite",
  framerMotion: "Framer Motion",
  django: "Django",
  postgresql: "PostgreSQL",
  ml: "Machine Learning",
  resend: "Resend",
  payload: "Payload CMS",
  fastapi: "FastAPI",
  sqlite: "SQLite",
};

export function getTechLabel(tech: string): string {
  return TECH_LABELS[tech] ?? tech.charAt(0).toUpperCase() + tech.slice(1);
}
